[project]
name = "pythonstreamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sazid", email = "sazidtec06@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.61.1",
]

[project.scripts]
pythonstreamlit = "pythonstreamlit:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
